menu:
    Blog: /
    Archive: /archives/
    # Categories: /categories/
    Twitter: https://twitter.com/TorresOmar
    GitHub: https://github.com/torresomar
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: kryptophsky
# duoshuo:

# Analytics
# google-analytics:
ga: UA-82749416-1

# Copyright Infomation
startyear: 2016
